image: Ubuntu1804  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew

build_script:
  - ./gradlew build
